### ISSUE TITLE
Post-Winter 22 Cleanup 

### ISSUE THREAD

**Issue by t-shoemaker** [ucdavisdatalab/adventures_in_data_science#11]
Here's a list of TODOs, now that the Winter 22 version of the course is over.
- [ ] Investigate the slowdown in the GitHub-hosted site
- [x] Make sure all code is quoted with backticks when referencing it in prose (#6)
- [x] Add a robust license
- [x] Add short discussion of delimiters in chapter 9 (#3)
- [x] Add section about R's recycling rules, either where vectors are first introduced or where indexing is introduced (#9)
- [x] Merge "a, b, etc." files into single files (example: the ones that support chapter 9)
- [x] Remove references chapter
